### ISSUE TITLE
Does the hosted site work?

### ISSUE THREAD

**Issue by nickcox** [tsearch-io/tsearch#30]
When I search from `https://tsearch.io/`, I get the error:

```
Access to fetch at 'https://gillchristian.xyz/ts-earch-api/search?query=xxx' from
origin 'https://tsearch.io' has been blocked by CORS policy: No 'Access-Control-Allow-
Origin' header is present on the requested resource. If an opaque response serves your
needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by gillchristian** [comment]
Hi. Thanks for reporting.

Yes, at the moment it's broken. I changed some stuff in my VPS and that broke it. I'm working on the fix. Will update the issue when is done.

**Comment by gillchristian** [comment]
Got it working finally!

[tsearch.io](https://tsearch.io) might not be up yet because of DNS but it's already up on [client.gillchristian.now.sh](https://client.gillchristian.now.sh/).
