### ISSUE TITLE
Something went wrong :(

### ISSUE THREAD

**Issue by Shou** [tsearch-io/tsearch#31]
I've followed the steps in the README

1. `yarn`
2. `yarn extract /my/sick/project/**/*.{ts,tsx}`
3. `yarn build && yarn start`

Then I get the error in the title: `Something went wrong :(`. What am I missing?

Things I've also tried:

* `fd '\.tsx?$' /my/sick/project | xargs yarn extract` to avoid `node_modules`
* `yarn watch` and `yarn dev` -> `No package found with the lifecycle script 'dev'`
* Using the Haskell backend, but that complains about `./modules.json` missing which isn't referenced anywhere else in the project so I don't know how to generate that

**Comment by gillchristian** [comment]
Hello Shou, the README is quite bad at the moment, it reflects an old iteration of the project. I will update it soon 🤞 

- The client is not the one from this repo anymore, is here now: https://github.com/tsearch-io/client
- As you mentioned, the backend should be the Haskell one (https://github.com/tsearch-io/server)
- `modules.json` is the file the extract script generates, you'll have a hard time generating that one. I also moved it to another repo and haven't pushed the code yet 😖

I will push my WIP and try to update the README a bit. I'll ping here when I do so.

I'm in the middle (or let's say beginning) of re-writing the search algorithm, so you'll probably get even worse results than now when searching 😬

**Comment by gillchristian** [comment]
I updated the readme of this and the other repos and pushed the indexer.

Let me know if you manage to run it locally.
